### ISSUE TITLE
Closing the window should close the app

### ISSUE THREAD

**Issue by mklarmann** [mcmunder/eaternity-react#27]

**Comment by mcmunder** [comment]
... that's actually not the default macOs behaviour. macOs apps keep running even when all windows are closed and have to be explicitly closed. But often it's more convenient when the app closes... So I'll change it.

**Comment by mklarmann** [comment]
yeah, the problem is, that one tries to start the app again, because you think it is closed. And nothing happens (and you have also no chance to bring up the window again). So you are stuck.
