### ISSUE TITLE
Allow multiple app instances

### ISSUE THREAD

**Issue by mklarmann** [mcmunder/eaternity-react#28]

**Comment by mcmunder** [comment]
This might be problematic... See [here](https://github.com/electron/electron/issues/2493) especially the last comment...

**Comment by mklarmann** [comment]
Ok. That is why atom does comment#3

**Comment by mklarmann** [comment]
so any solution with multiple edit windows so has to go with tabs...

**Comment by mcmunder** [comment]
... yeah, tabs are a good idea! I'll add this feature as a new issue!

**Comment by mcmunder** [comment]
Closing because not possible or very tricky. #38 as possible solution.
