### ISSUE TITLE
sort order JSON properties

### ISSUE THREAD

**Issue by mcmunder** [mcmunder/eaternity-react#29]

**Comment by mcmunder** [comment]
Do you mean: sort the input fields in the edit view alphabetically? Should this  influence the view only or also the json files?!

**Comment by mklarmann** [comment]
I meant the sort order is broken, because they get resorted. Sorry. The order should be as in the orginal JSON file. Always.

**Comment by mcmunder** [comment]
Closed because duplicate to #19
